-- Funções RPC para manter Supabase ativo e evitar congelamento
-- Executado pelo GitHub Actions a cada 6 horas

-- Função 1: health_check - Verificação básica de saúde
CREATE OR REPLACE FUNCTION health_check()
RETURNS TABLE (
  status TEXT,
  message TEXT,
  timestamp TIMESTAMPTZ
) AS $$
BEGIN
  RETURN 
    SELECT 
      'healthy'::TEXT as status,
      'Supabase RPC funcionando corretamente'::TEXT as message,
      NOW()::TIMESTAMPTZ as timestamp;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Função 2: ping_keep_alive - Mantém conexão ativa
CREATE OR REPLACE FUNCTION ping_keep_alive(timestamp_input TIMESTAMP WITH TIME ZONE)
RETURNS TABLE (
  success BOOLEAN,
  message TEXT,
  server_time TIMESTAMPTZ,
  client_time TIMESTAMPTZ
) AS $$
BEGIN
  DECLARE 
    time_diff INTERVAL;
    success_val BOOLEAN := TRUE;
    message_val TEXT := 'Ping recebido com sucesso';
    
  BEGIN
    -- Calcular diferença de tempo
    time_diff := EXTRACT(EPOCH FROM (NOW() - timestamp_input));
    
    -- Considerar sucesso se diferença for menor que 5 minutos
    IF time_diff > 300 THEN
      success_val := FALSE;
      message_val := 'Atraso detectado: ' || EXTRACT(SECONDS FROM time_diff) || ' segundos';
    END IF;
    
    RETURN 
      SELECT 
        success_val as success,
        message_val as message,
        NOW() as server_time,
        timestamp_input as client_time;
  END;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Função 3: get_project_status - Status completo do projeto
CREATE OR REPLACE FUNCTION get_project_status()
RETURNS TABLE (
  project_name TEXT,
  status TEXT,
  last_ping TIMESTAMPTZ,
  tables_count INTEGER,
  active_connections INTEGER
) AS $$
BEGIN
  DECLARE
    tables_count_val INTEGER;
    
  -- Contar tabelas principais
  SELECT COUNT(*) INTO tables_count_val
  FROM information_schema.tables 
  WHERE table_schema = 'public' 
  AND table_type = 'BASE TABLE';
  
  RETURN
    SELECT 
      'NovaesWeb'::TEXT as project_name,
      CASE 
        WHEN tables_count_val > 0 THEN 'ativo'
        ELSE 'configurando'
      END::TEXT as status,
      NOW()::TIMESTAMPTZ as last_ping,
      tables_count_val as INTEGER,
      1::INTEGER as active_connections;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Função 4: cleanup_old_pings - Limpar pings antigos (opcional)
CREATE OR REPLACE FUNCTION cleanup_old_pings()
RETURNS INTEGER AS $$
BEGIN
  -- Esta função pode ser chamada periodicamente para limpar registros antigos
  DELETE FROM ping_logs 
  WHERE created_at < NOW() - INTERVAL '7 days';
  
  RETURN ROW_COUNT();
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Tabela para log de pings (opcional, para monitoramento)
CREATE TABLE IF NOT EXISTS ping_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  success BOOLEAN DEFAULT TRUE,
  message TEXT,
  response_time_ms INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Índice para performance
CREATE INDEX IF NOT EXISTS idx_ping_logs_timestamp ON ping_logs(timestamp);
CREATE INDEX IF NOT EXISTS idx_ping_logs_success ON ping_logs(success);

-- Função 5: test_connection - Teste completo de conexão
CREATE OR REPLACE FUNCTION test_connection()
RETURNS TABLE (
  api_status TEXT,
  db_status TEXT,
  auth_status TEXT,
  response_time_ms INTEGER,
  timestamp TIMESTAMPTZ
) AS $$
DECLARE
    start_time TIMESTAMP WITH TIME ZONE;
    end_time TIMESTAMP WITH TIME ZONE;
    response_time INTEGER;
BEGIN
  start_time := NOW();
  
  -- Testar API REST
  PERFORM pg_sleep(0.1); -- Simular processamento
  
  end_time := NOW();
  response_time := EXTRACT(MILLISECONDS FROM (end_time - start_time));
  
  RETURN
    SELECT 
      CASE 
        WHEN response_time < 1000 THEN 'excelente'
        WHEN response_time < 2000 THEN 'bom'
        ELSE 'lento'
      END::TEXT as api_status,
      'conectado'::TEXT as db_status,
      'funcionando'::TEXT as auth_status,
      response_time as response_time_ms,
      end_time as timestamp;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Grant de permissões (executar como admin)
-- NOTA: Ajuste os nomes de usuário/schema conforme necessário
-- GRANT EXECUTE ON FUNCTION health_check() TO authenticated;
-- GRANT EXECUTE ON FUNCTION ping_keep_alive() TO authenticated;
-- GRANT EXECUTE ON FUNCTION get_project_status() TO authenticated;
-- GRANT EXECUTE ON FUNCTION test_connection() TO authenticated;

-- Comandos úteis para teste:
/*
-- Testar health_check:
SELECT * FROM health_check();

-- Testar ping_keep_alive:
SELECT * FROM ping_keep_alive(NOW());

-- Testar status completo:
SELECT * FROM get_project_status();

-- Testar conexão:
SELECT * FROM test_connection();
*/
