-- Funções RPC para o sistema de Ping do NovaesWeb
-- Execute este SQL no seu Supabase SQL Editor

-- Função 1: health_check - Verificação básica
CREATE OR REPLACE FUNCTION health_check()
RETURNS TABLE (
  status TEXT,
  message TEXT,
  timestamp TIMESTAMPTZ,
  project_name TEXT
) AS $$
BEGIN
  RETURN 
    SELECT 
      'healthy'::TEXT as status,
      'NovaesWeb Supabase RPC funcionando corretamente'::TEXT as message,
      NOW()::TIMESTAMPTZ as timestamp,
      'NovaesWeb'::TEXT as project_name;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Função 2: ping_keep_alive - Mantém conexão ativa
CREATE OR REPLACE FUNCTION ping_keep_alive(timestamp_input TIMESTAMP WITH TIME ZONE DEFAULT NOW())
RETURNS TABLE (
  success BOOLEAN,
  message TEXT,
  server_time TIMESTAMPTZ,
  client_time TIMESTAMPTZ,
  time_diff_seconds INTEGER
) AS $$
BEGIN
  DECLARE 
    time_diff INTERVAL;
    time_diff_seconds_val INTEGER;
    success_val BOOLEAN := TRUE;
    message_val TEXT := 'Ping recebido com sucesso';
    
  BEGIN
    -- Calcular diferença de tempo
    time_diff := EXTRACT(EPOCH FROM (NOW() - timestamp_input));
    time_diff_seconds_val := EXTRACT(SECONDS FROM time_diff);
    
    -- Considerar sucesso se diferença for menor que 5 minutos
    IF time_diff_seconds_val > 300 THEN
      success_val := FALSE;
      message_val := 'Atraso detectado: ' || time_diff_seconds_val || ' segundos';
    END IF;
    
    RETURN 
      SELECT 
        success_val as success,
        message_val as message,
        NOW() as server_time,
        timestamp_input as client_time,
        time_diff_seconds_val as time_diff_seconds;
  END;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Função 3: get_project_status - Status completo do projeto
CREATE OR REPLACE FUNCTION get_project_status()
RETURNS TABLE (
  project_name TEXT,
  status TEXT,
  last_ping TIMESTAMPTZ,
  tables_count INTEGER,
  active_connections INTEGER,
  database_size_mb NUMERIC
) AS $$
BEGIN
  DECLARE
    tables_count_val INTEGER;
    db_size_val NUMERIC;
    
  -- Contar tabelas principais
  SELECT COUNT(*) INTO tables_count_val
  FROM information_schema.tables 
  WHERE table_schema = 'public' 
  AND table_type = 'BASE TABLE';
  
  -- Obter tamanho do banco
  SELECT pg_database_size(current_database()) / 1024 / 1024 INTO db_size_val;
  
  RETURN
    SELECT 
      'NovaesWeb'::TEXT as project_name,
      CASE 
        WHEN tables_count_val > 0 THEN 'ativo'
        ELSE 'configurando'
      END::TEXT as status,
      NOW()::TIMESTAMPTZ as last_ping,
      tables_count_val as INTEGER,
      1::INTEGER as active_connections,
      db_size_val as NUMERIC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Função 4: test_connection - Teste completo de conexão
CREATE OR REPLACE FUNCTION test_connection()
RETURNS TABLE (
  api_status TEXT,
  db_status TEXT,
  auth_status TEXT,
  response_time_ms INTEGER,
  timestamp TIMESTAMPTZ,
  server_info TEXT
) AS $$
DECLARE
    start_time TIMESTAMP WITH TIME ZONE;
    end_time TIMESTAMP WITH TIME ZONE;
    response_time INTEGER;
    server_info_val TEXT;
BEGIN
  start_time := NOW();
  
  -- Simular processamento e testar conexão
  PERFORM pg_sleep(0.01); -- 10ms de delay para simular processamento
  
  end_time := NOW();
  response_time := EXTRACT(MILLISECONDS FROM (end_time - start_time));
  
  -- Obter informações do servidor
  SELECT version() INTO server_info_val;
  
  RETURN
    SELECT 
      CASE 
        WHEN response_time < 100 THEN 'excelente'
        WHEN response_time < 500 THEN 'bom'
        ELSE 'lento'
      END::TEXT as api_status,
      'conectado'::TEXT as db_status,
      'funcionando'::TEXT as auth_status,
      response_time as response_time_ms,
      end_time as timestamp,
      SUBSTRING(server_info_val, 1, 100) as server_info;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Criar tabela para logs de ping (opcional)
CREATE TABLE IF NOT EXISTS ping_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  success BOOLEAN DEFAULT TRUE,
  message TEXT,
  response_time_ms INTEGER,
  client_timestamp TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Índices para performance
CREATE INDEX IF NOT EXISTS idx_ping_logs_timestamp ON ping_logs(timestamp);
CREATE INDEX IF NOT EXISTS idx_ping_logs_success ON ping_logs(success);

-- Grant de permissões para execução
-- NOTA: Ajuste os nomes de usuário conforme necessário
GRANT EXECUTE ON FUNCTION health_check() TO authenticated, anon, service_role;
GRANT EXECUTE ON FUNCTION ping_keep_alive(TIMESTAMP WITH TIME ZONE) TO authenticated, anon, service_role;
GRANT EXECUTE ON FUNCTION get_project_status() TO authenticated, anon, service_role;
GRANT EXECUTE ON FUNCTION test_connection() TO authenticated, anon, service_role;

-- Teste das funções (descomente para testar)
/*
SELECT * FROM health_check();
SELECT * FROM ping_keep_alive(NOW());
SELECT * FROM get_project_status();
SELECT * FROM test_connection();
*/

-- Confirmar criação
SELECT 'Funções RPC criadas com sucesso!' as status, NOW() as timestamp;
