// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvxlbvfryzmocrafhfjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12eGxidmZyeXptb2NyYWZoZmpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5MTgwOTMsImV4cCI6MjA4OTQ5NDA5M30.l3vZib37kooIIMUSdW7dybSYr-4-OsCnq9l0ezyJ2oQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});