// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { IS_USING_SUPABASE_FALLBACK, PUBLIC_SUPABASE_CONFIG } from './public-config';

const { url: SUPABASE_URL, publishableKey: SUPABASE_PUBLISHABLE_KEY } = PUBLIC_SUPABASE_CONFIG;

if (IS_USING_SUPABASE_FALLBACK) {
  console.warn("Supabase VITE variables are missing. Using public fallback configuration.");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
