name: Ping Supabase

on:
  schedule:
    - cron: "1/5 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Chamar endpoint
        run: curl --fail -s https://novaesweb.site/api/ping
